### ISSUE TITLE
Not issue but question

### ISSUE THREAD

**Issue by bayartsogt-ya** [kbatsuren/monwn#1]
Thank you for the great work!

There are some "null"s in first column.

I just wondered what is the first column? 

I thought it was the identifier of lemma and its synonyms and examples.

Example: (Line: 61-68)
'''
null	mon:lemma	гойд
null	mon:lemma	сүртэй юм
null	mon:lemma	сонин юм
null	mon:lemma	ховор
null	mon:lemma	ер бус
null	mon:lemma	онцгой
null	mon:lemma	өчүүхэн
null	mon:lemma	хоосон
'''

**Comment by kbatsuren** [comment]
Thanks for pointing out this issue.

FYI, It should be the synset identifier of lemmas. We will fix it as soon as possible.

**Comment by kbatsuren** [comment]
This issue is fixed thanks.

**Comment by kbatsuren** [comment]
We also added more details on the format.
